language: node_js

node_js:
  - node

cache:
  yarn: true

services:
  - mysql

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('123456') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'create database test;'

after_success:
  - yarn run coveralls
